apiVersion: v1
kind: ServiceAccount
metadata:
  name: logging-service-operator
  labels:
    name: logging-service-operator
    app.kubernetes.io/name: logging-service-operator
    app.kubernetes.io/component: logging-operator
    app.kubernetes.io/part-of: logging
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
