{{- if .Values.fluentbit.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logging-fluentbit
  labels:
    {{- include "logging-operator.resourceLabels" (dict "ctx" . "name" "logging-fluentbit" "component" "fluentbit") | nindent 4 }}
  {{- if .Values.fluentbit.labels }}
    {{- toYaml .Values.fluentbit.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.fluentbit.annotations }}
  annotations:
    {{- toYaml .Values.fluentbit.annotations | nindent 4 }}
  {{- end }}
{{- end }}
