apiVersion: v1
kind: Service
metadata:
  name: events-reader
  namespace: {{ .Release.Namespace }}
  labels: {}
spec:
  selector:
    name: events-reader
  ports:
    - name: events-reader
      port: 8080
      protocol: TCP
      targetPort: 8080
