{{- if .Values.cloudEventsReader.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: events-reader
  labels:
    name: events-reader
    app.kubernetes.io/name: events-reader
    app.kubernetes.io/component: events-reader
    app.kubernetes.io/part-of: logging
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- if .Values.cloudEventsReader.labels }}
    {{- toYaml .Values.cloudEventsReader.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.cloudEventsReader.annotations }}
  annotations:
    {{- toYaml .Values.cloudEventsReader.annotations | nindent 4 }}
  {{- end }}
{{- end }}
