{{- if .Values.cloudEventsReader.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: events-reader
  labels:
    {{- include "logging-operator.resourceLabels" (dict "ctx" . "name" "events-reader" "component" "events-reader") | nindent 4 }}
  {{- if .Values.cloudEventsReader.labels }}
    {{- toYaml .Values.cloudEventsReader.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.cloudEventsReader.annotations }}
  annotations:
    {{- toYaml .Values.cloudEventsReader.annotations | nindent 4 }}
  {{- end }}
{{- end }}
