apiVersion: v1
kind: Service
metadata:
  name: logging-fluentd
  namespace: {{ .Release.Namespace }}
  labels:
    component: logging-fluentd
{{- if .Values.OpenshiftDeploy }}
    provider: openshift
{{- else }}
    provider: kubernetes
{{- end }}
spec:
  selector:
    name: logging-fluentd
  ports:
    - name: logging-fluentd
      port: 24220
      protocol: TCP
      targetPort: 24220
