{{- if .Values.integrationTests.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.integrationTests.service.name }}
  labels:
    {{- include "logging-operator.resourceLabels" (dict "ctx" . "name" .Values.integrationTests.service.name "component" "integration-tests") | nindent 4 }}
    app.kubernetes.io/instance: {{ cat .Values.integrationTests.service.name "-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    {{- $image := include "logging-integration-tests.image" . }}
    app.kubernetes.io/version: {{ splitList ":" $image | last | quote }}
  {{- if .Values.integrationTests.labels }}
    {{- toYaml .Values.integrationTests.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.integrationTests.annotations }}
  annotations:
    {{- toYaml .Values.integrationTests.annotations | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.integrationTests.service.name }}
roleRef:
  kind: Role
  name: {{ .Values.integrationTests.service.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
