{{- if .Values.integrationTests.install }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.integrationTests.service.name }}-secret
  labels:
    {{- include "logging-operator.resourceLabels" (dict "ctx" . "name" (printf "%s-secret" .Values.integrationTests.service.name) "component" "integration-tests") | nindent 4 }}
  {{- if .Values.integrationTests.labels }}
    {{- toYaml .Values.integrationTests.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.integrationTests.annotations }}
  annotations:
    {{- toYaml .Values.integrationTests.annotations | nindent 4 }}
  {{- end }}
stringData:
  graylog-user: "{{ .Values.graylog.user }}"
  graylog-password: "{{ .Values.graylog.password }}"
  vm-user: {{ .Values.integrationTests.vmUser | default "" | quote }}
  ssh-key: {{ .Values.integrationTests.sshKey | default "" | quote }}
{{- end }}
