{{- if .Values.integrationTests.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.integrationTests.service.name }}
  labels:
    {{- include "logging-operator.resourceLabels" (dict "ctx" . "name" .Values.integrationTests.service.name "component" "integration-tests") | nindent 4 }}
  {{- if .Values.integrationTests.labels }}
    {{- toYaml .Values.integrationTests.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.integrationTests.annotations }}
  annotations:
    {{- toYaml .Values.integrationTests.annotations | nindent 4 }}
  {{- end }}
{{- end }}
